#!/usr/bin/env python3
"""
Niche configuration for all 10 supported categories.
Each niche has subjects with the same prompt parameters as zodiac_config.py.
"""

NICHES: dict[str, dict] = {
    "office_burnout": {
        "name": "Office Burnout",
        "emoji": "💼",
        "description": "For stressed workers, remote employees, and meeting survivors",
        "simbolo_angolo": "tiny laptop computer with tired face stylized decorative element",
        "simbolo_lato": "small cute coffee cup with steam",
        "subjects": [
            {
                "key": "desk_chaos",
                "label": "Scrivania del Caos",
                "simbolo_angolo": "tiny laptop computer with tired face stylized decorative element",
                "simbolo_lato": "small cute coffee cup with steam",
                "soggetto_kawaii": "adorable kawaii office desk completely covered in papers, sticky notes, and coffee cups, with a tiny stressed computer monitor with big sad eyes and a kawaii stapler hiding behind a paper mountain",
            },
            {
                "key": "email_tsunami",
                "label": "Tsunami di Email",
                "simbolo_angolo": "tiny envelope with wings stylized decorative element",
                "simbolo_lato": "small cute envelope with X eyes",
                "soggetto_kawaii": "one cute kawaii office worker drowning in a wave made entirely of tiny email envelopes, arms reaching up with a desperate but funny expression, tiny notification bubbles floating everywhere",
            },
            {
                "key": "zoom_fatigue",
                "label": "Zoom Fatigue",
                "simbolo_angolo": "tiny computer screen with video call stylized decorative element",
                "simbolo_lato": "small cute camera with tired eyes",
                "soggetto_kawaii": "adorable kawaii character sitting at a computer during a video call, surrounded by 9 tiny windows each with a different exhausted face, the character's hair is messy but only visible from the shoulders up",
            },
            {
                "key": "printer_rage",
                "label": "La Stampante Nemica",
                "simbolo_angolo": "tiny printer with devil horns stylized decorative element",
                "simbolo_lato": "small cute paper jam warning sign",
                "soggetto_kawaii": "a kawaii printer being hugged menacingly by a frustrated but adorable office worker, the printer has tiny devil horns and an evil grin, paper jam warnings floating around like confetti",
            },
            {
                "key": "monday_dread",
                "label": "Odio il Lunedì",
                "simbolo_angolo": "tiny calendar with crying face on Monday stylized decorative element",
                "simbolo_lato": "small cute alarm clock with sad face",
                "soggetto_kawaii": "one chibi kawaii character dramatically clinging to a giant bed pillow, tiny calendar showing Monday in the background with a scary face, tiny ZZZ bubbles and coffee cups floating around",
            },
            {
                "key": "coffee_dependency",
                "label": "Caffè o Morte",
                "simbolo_angolo": "tiny coffee bean with crown stylized decorative element",
                "simbolo_lato": "small cute espresso cup with happy face",
                "soggetto_kawaii": "one adorable kawaii character hugging a coffee cup three times their size like it's their best friend, tiny heart eyes, steam forming little hearts, surrounded by scattered coffee beans and tiny coffee cups",
            },
        ],
    },

    "astrology": {
        "name": "Astrology & Zodiac",
        "emoji": "⭐",
        "description": "For zodiac enthusiasts, astrology fans, Mercury Retrograde survivors",
        "subjects": "zodiac",  # Uses zodiac_config.py — 12 signs
    },

    "nurses_healthcare": {
        "name": "Nurses & Healthcare",
        "emoji": "🏥",
        "description": "For nurses, healthcare workers, and night-shift survivors",
        "simbolo_angolo": "tiny stethoscope stylized decorative element",
        "simbolo_lato": "small cute medical cross with heart",
        "subjects": [
            {
                "key": "night_shift",
                "label": "Turno di Notte",
                "simbolo_angolo": "tiny stethoscope stylized decorative element",
                "simbolo_lato": "small cute medical cross with heart",
                "soggetto_kawaii": "one exhausted but adorable kawaii nurse with big tired eyes holding a giant coffee IV drip attached to their arm, surrounded by tiny moon and star symbols, night shift schedule in the background",
            },
            {
                "key": "patient_bell",
                "label": "Il Campanellino Infernale",
                "simbolo_angolo": "tiny hospital bell stylized decorative element",
                "simbolo_lato": "small cute call button with face",
                "soggetto_kawaii": "one kawaii nurse surrounded by dozens of floating call bells all ringing at once, the nurse has a serene smile while chaos erupts around them, tiny patient beds with cute faces peeking over",
            },
            {
                "key": "er_chaos",
                "label": "Pronto Soccorso",
                "simbolo_angolo": "tiny ambulance with cute face stylized decorative element",
                "simbolo_lato": "small cute bandage with smile",
                "soggetto_kawaii": "adorable kawaii scene of a hospital corridor where everything is happening at once — a cute rolling IV pole, a kawaii wheelchair zooming past, and a nurse calmly sipping coffee in the center of the storm",
            },
            {
                "key": "scrubs_hero",
                "label": "Supereroe in Camice",
                "simbolo_angolo": "tiny superhero cape with medical cross stylized decorative element",
                "simbolo_lato": "small cute pill with wings",
                "soggetto_kawaii": "one kawaii nurse dressed as a superhero with a cape made of hospital scrubs, stethoscope as a lasso, flying above a tiny hospital with a determined smile and big sparkly eyes",
            },
            {
                "key": "charting_nightmare",
                "label": "Burocrazia Ospedaliera",
                "simbolo_angolo": "tiny clipboard with crying face stylized decorative element",
                "simbolo_lato": "small cute pen with determination",
                "soggetto_kawaii": "one cute kawaii nurse buried under a mountain of medical charts and clipboards, only their head visible, surrounded by floating tiny checkboxes, pens, and a computer screen with endless forms",
            },
            {
                "key": "end_of_shift",
                "label": "Fine del Turno",
                "simbolo_angolo": "tiny clock with finish line stylized decorative element",
                "simbolo_lato": "small cute exit door with halo",
                "soggetto_kawaii": "one absolutely exhausted kawaii nurse at the end of their shift, shoes leaving little hearts as they walk out, carrying a giant coffee, scrubs slightly disheveled but a victorious smile on their face",
            },
        ],
    },

    "teachers": {
        "name": "Teachers",
        "emoji": "🍎",
        "description": "For teachers, educators, and chalk-dust survivors",
        "simbolo_angolo": "tiny apple with graduation cap stylized decorative element",
        "simbolo_lato": "small cute pencil with smile",
        "subjects": [
            {
                "key": "grading_mountain",
                "label": "La Montagna di Compiti",
                "simbolo_angolo": "tiny apple with graduation cap stylized decorative element",
                "simbolo_lato": "small cute pencil with smile",
                "soggetto_kawaii": "one adorable kawaii teacher buried under a mountain of papers and essays to grade, red pen in hand, only their head visible, tiny grade stamps floating around them like confetti",
            },
            {
                "key": "classroom_chaos",
                "label": "Classe del Terrore",
                "simbolo_angolo": "tiny chalkboard with math formula stylized decorative element",
                "simbolo_lato": "small cute eraser with happy face",
                "soggetto_kawaii": "one kawaii teacher standing at the front of class with a serene smile while tiny student desks are in complete chaos around them, paper airplanes flying, pencils rolling, the teacher holding a coffee cup unfazed",
            },
            {
                "key": "parent_emails",
                "label": "Email dei Genitori",
                "simbolo_angolo": "tiny envelope with parent face stylized decorative element",
                "simbolo_lato": "small cute phone with notification bubble",
                "soggetto_kawaii": "one kawaii teacher staring at a computer screen full of parent emails, each email represented as a tiny screaming face, the teacher maintains a calm smile while holding a stress ball",
            },
            {
                "key": "summer_countdown",
                "label": "Countdown Estate",
                "simbolo_angolo": "tiny sun with sunglasses stylized decorative element",
                "simbolo_lato": "small cute calendar with X marks",
                "soggetto_kawaii": "one ecstatically happy kawaii teacher crossing off days on a giant calendar, summer beach items hidden everywhere — tiny sunscreen, sunglasses peeking from the desk drawer, flip flops under the desk",
            },
            {
                "key": "supply_closet",
                "label": "Compro Tutto Io",
                "simbolo_angono": "tiny receipt with sad face stylized decorative element",
                "simbolo_angolo": "tiny receipt with sad face stylized decorative element",
                "simbolo_lato": "small cute pencil box with coins",
                "soggetto_kawaii": "one determined kawaii teacher pushing a giant shopping cart overflowing with school supplies at a store, a stack of their own receipts trailing behind, expression equal parts resigned and heroic",
            },
            {
                "key": "copy_machine",
                "label": "La Fotocopiatrice Rotta",
                "simbolo_angolo": "tiny copy machine with smoke stylized decorative element",
                "simbolo_lato": "small cute paper with error face",
                "soggetto_kawaii": "one kawaii teacher in a battle stance facing a giant evil copy machine that is spewing papers everywhere, jam lights flashing, the teacher wielding a broom like a sword with a determined expression",
            },
        ],
    },

    "stressed_moms": {
        "name": "Stressed Moms",
        "emoji": "👩‍👧",
        "description": "For moms, tired parents, and school run survivors",
        "simbolo_angolo": "tiny baby bottle with heart stylized decorative element",
        "simbolo_lato": "small cute pacifier with face",
        "subjects": [
            {
                "key": "mom_taxi",
                "label": "Taxi Mamma",
                "simbolo_angolo": "tiny car with child faces in windows stylized decorative element",
                "simbolo_lato": "small cute calendar with activities",
                "soggetto_kawaii": "one exhausted kawaii mom in a car surrounded by tiny children bouncing everywhere, snack wrappers floating, soccer gear piled up, the mom has serene eyes and a coffee in hand while chaos reigns",
            },
            {
                "key": "homework_battle",
                "label": "Battaglia dei Compiti",
                "simbolo_angolo": "tiny textbook crying stylized decorative element",
                "simbolo_lato": "small cute pencil with battle scar",
                "soggetto_kawaii": "one kawaii mom and tiny child facing each other across a homework-covered table like a chess match, both determined, math worksheets and eraser debris everywhere, clock showing midnight in the background",
            },
            {
                "key": "school_chat",
                "label": "La Chat Scolastica",
                "simbolo_angolo": "tiny phone exploding with messages stylized decorative element",
                "simbolo_lato": "small cute message bubble with spiral",
                "soggetto_kawaii": "one kawaii mom staring at a phone screen covered in WhatsApp group message bubbles, each bubble with a different parent emoji face, the mom's expression is a mix of overwhelmed and resigned",
            },
            {
                "key": "invisible_work",
                "label": "Carico Mentale",
                "simbolo_angolo": "tiny brain overflowing with lists stylized decorative element",
                "simbolo_lato": "small cute checklist with infinite items",
                "soggetto_kawaii": "one kawaii mom with a thought bubble above her head containing a hundred tiny items — doctor appointments, grocery lists, school events, birthday gifts — while calmly cooking dinner with multiple arms",
            },
            {
                "key": "kids_sick",
                "label": "Tutti Malati Tranne Me",
                "simbolo_angolo": "tiny thermometer with face stylized decorative element",
                "simbolo_lato": "small cute tissue box with sad face",
                "soggetto_kawaii": "one kawaii mom in hazmat-style pajamas surrounded by sick children each wrapped in blankets, the mom holding multiple medicines and soups simultaneously, a halo of exhaustion over their head",
            },
            {
                "key": "three_am",
                "label": "Le 3 di Notte",
                "simbolo_angolo": "tiny moon with crying face stylized decorative element",
                "simbolo_lato": "small cute star with pillow",
                "soggetto_kawaii": "one zombie-like but adorable kawaii mom shuffling down a dark hallway at 3am, tiny child pulling their hand, the mom's eyes half-closed but still holding a bottle ready, stars and ZZZ floating around their head",
            },
        ],
    },

    "social_anxiety": {
        "name": "Social Anxiety",
        "emoji": "🙈",
        "description": "For introverts, overthinkers, and plan-cancellers",
        "simbolo_angolo": "tiny hiding figure behind curtain stylized decorative element",
        "simbolo_lato": "small cute phone with unread bubble",
        "subjects": [
            {
                "key": "cancel_plans",
                "label": "Piani Cancellati",
                "simbolo_angolo": "tiny calendar with big X stylized decorative element",
                "simbolo_lato": "small cute couch with heart",
                "soggetto_kawaii": "one adorably happy kawaii character cancelling plans on their phone while already in pajamas on the couch, surrounded by snacks and blankets, the happiest expression possible, tiny confetti celebrating the cancellation",
            },
            {
                "key": "phone_call_dread",
                "label": "Telefonata Inaspettata",
                "simbolo_angolo": "tiny ringing phone with horror face stylized decorative element",
                "simbolo_lato": "small cute phone hiding behind pillow",
                "soggetto_kawaii": "one kawaii character staring in absolute terror at a ringing phone, backing away slowly, the phone has an innocent happy face unaware of the panic it's causing, tiny sweat drops everywhere",
            },
            {
                "key": "battery_drained",
                "label": "Batteria Sociale Scarica",
                "simbolo_angolo": "tiny battery at 2% stylized decorative element",
                "simbolo_lato": "small cute power outlet with zzz",
                "soggetto_kawaii": "one kawaii introvert character with a literal battery gauge showing 2% after a social event, dragging themselves home, home in the background glowing like a beacon, slippers waiting by the door",
            },
            {
                "key": "overthinking",
                "label": "Overthinking Champion",
                "simbolo_angolo": "tiny brain with lightning bolts stylized decorative element",
                "simbolo_lato": "small cute thought bubble with spiral",
                "soggetto_kawaii": "one kawaii character lying in bed surrounded by floating thought bubbles, each containing a tiny scenario — that thing they said in 2015, tomorrow's awkward situation, what if they said X instead of Y, all labeled with tiny timestamps",
            },
            {
                "key": "party_escape",
                "label": "La Fuga dalla Festa",
                "simbolo_angolo": "tiny exit door with halo stylized decorative element",
                "simbolo_lato": "small cute clock showing party start time",
                "soggetto_kawaii": "one kawaii character at a party secretly plotting their escape route, mentally calculating the minimum socially acceptable time before leaving, surrounded by oblivious party guests, a tiny countdown timer floating above their head",
            },
            {
                "key": "read_not_replied",
                "label": "Letto, Non Risposto",
                "simbolo_angolo": "tiny double checkmark with guilty face stylized decorative element",
                "simbolo_lato": "small cute message marked as read",
                "soggetto_kawaii": "one kawaii character staring at a phone message marked as read, visibly overwhelmed by the need to craft the perfect reply, drafts floating around as little clouds, each draft crossed out, meanwhile the read receipt glowing accusatorially",
            },
        ],
    },

    "true_crime": {
        "name": "True Crime",
        "emoji": "🔍",
        "description": "For true crime podcast fans, documentary watchers, and amateur detectives",
        "simbolo_angolo": "tiny magnifying glass with detective hat stylized decorative element",
        "simbolo_lato": "small cute evidence bag with heart",
        "subjects": [
            {
                "key": "conspiracy_board",
                "label": "La Board dei Sospetti",
                "simbolo_angolo": "tiny cork board with red string stylized decorative element",
                "simbolo_lato": "small cute pushpin with clue",
                "soggetto_kawaii": "one adorably obsessed kawaii detective in front of a giant mystery board covered in photos, clues, and red string connecting everything, intense focused eyes, magnifying glass in hand, coffee cup labeled evidence",
            },
            {
                "key": "podcast_listener",
                "label": "Podcast alle 3 di Notte",
                "simbolo_angolo": "tiny podcast microphone with skull stylized decorative element",
                "simbolo_lato": "small cute headphone with case file",
                "soggetto_kawaii": "one kawaii character in bed with headphones on at 3am listening to true crime podcast, completely wide awake and terrified but unable to stop, phone glowing in the dark, shadow of every object looking suspicious",
            },
            {
                "key": "suspicious_neighbor",
                "label": "Il Vicino Sospetto",
                "simbolo_angolo": "tiny binoculars with notebook stylized decorative element",
                "simbolo_lato": "small cute curtain slightly parted",
                "soggetto_kawaii": "one kawaii character peeking through curtains with binoculars, taking detailed notes about the neighbor doing completely normal things, tiny notebook labeled suspects, expression of extreme suspicion",
            },
            {
                "key": "crime_scene_fan",
                "label": "Fan dei Documentari",
                "simbolo_angolo": "tiny TV with crime scene tape stylized decorative element",
                "simbolo_lato": "small cute popcorn with detective hat",
                "soggetto_kawaii": "one kawaii character watching a true crime documentary with a giant bowl of popcorn, completely engrossed, surrounding themselves with notes and theories written on tiny post-its, friends texting them but ignored",
            },
            {
                "key": "amateur_detective",
                "label": "Detective Dilettante",
                "simbolo_angolo": "tiny deerstalker hat with magnifying glass stylized decorative element",
                "simbolo_lato": "small cute pipe with question mark",
                "soggetto_kawaii": "one kawaii character dressed as a detective with oversized coat and hat, solving a mystery board about something completely mundane like who ate the last cookie, applying full FBI-level analysis with tiny clue arrows and labels",
            },
            {
                "key": "cold_case",
                "label": "Cold Case Ossessione",
                "simbolo_angolo": "tiny file folder labeled COLD CASE stylized decorative element",
                "simbolo_lato": "small cute evidence photo with timestamp",
                "soggetto_kawaii": "one determined kawaii character surrounded by stacked cold case files, wall covered in timelines and maps, pointing dramatically at a clue, half-eaten snacks suggesting they've been at it for hours, a cat as loyal companion",
            },
        ],
    },

    "coffee_lovers": {
        "name": "Coffee Lovers",
        "emoji": "☕",
        "description": "For coffee addicts, barista fans, and people who function only on caffeine",
        "simbolo_angolo": "tiny coffee bean with crown stylized decorative element",
        "simbolo_lato": "small cute espresso cup with heart",
        "subjects": [
            {
                "key": "morning_ritual",
                "label": "Il Rituale del Mattino",
                "simbolo_angolo": "tiny coffee bean with crown stylized decorative element",
                "simbolo_lato": "small cute espresso cup with heart",
                "soggetto_kawaii": "one kawaii character before and after coffee on the same illustration — left side: zombie with X eyes, right side: radiant with stars and hearts — divided by a giant magical coffee cup in the center",
            },
            {
                "key": "coffee_worship",
                "label": "La Santa Macchinetta",
                "simbolo_angolo": "tiny espresso machine with halo stylized decorative element",
                "simbolo_lato": "small cute coffee drop with wings",
                "soggetto_kawaii": "one adorable kawaii character kneeling in reverence before a giant glowing espresso machine on a pedestal, tiny coffee beans arranged like candles, steam rising in the shape of a halo, pure devotion",
            },
            {
                "key": "latte_art",
                "label": "Latte Art Terapia",
                "simbolo_angono": "tiny milk pitcher with artistic foam stylized decorative element",
                "simbolo_angolo": "tiny milk pitcher with artistic foam stylized decorative element",
                "simbolo_lato": "small cute leaf-pattern foam art",
                "soggetto_kawaii": "one happy kawaii barista creating latte art, the foam forming a tiny portrait of the coffee cup itself, surrounded by happy coffee cup characters admiring the artwork, tiny heart shapes and stars floating",
            },
            {
                "key": "cold_brew",
                "label": "Cold Brew Devoto",
                "simbolo_angolo": "tiny glass jar with cold brew and ice stylized decorative element",
                "simbolo_lato": "small cute ice cube with happy face",
                "soggetto_kawaii": "one kawaii character cradling a giant mason jar of cold brew like a precious treasure, surrounded by summer heat waves but perfectly cool, tiny coffee beans orbiting the jar like planets, sun glaring jealously",
            },
            {
                "key": "caffeine_iv",
                "label": "La Flebo di Caffè",
                "simbolo_angolo": "tiny IV drip bag with coffee stylized decorative element",
                "simbolo_lato": "small cute syringe with espresso",
                "soggetto_kawaii": "one kawaii office character connected to a coffee IV drip instead of saline, looking immediately revived and productive, the IV bag shaped like a coffee cup with a happy face, tiny productivity sparks flying",
            },
            {
                "key": "coffee_order",
                "label": "L'Ordine Impossibile",
                "simbolo_angolo": "tiny receipt of a long coffee order stylized decorative element",
                "simbolo_lato": "small cute barista with notepad",
                "soggetto_kawaii": "one kawaii character ordering an incredibly complicated coffee at a cafe, the order floating above their head as a long detailed scroll, the barista kawaii face frozen in a terrified smile, both characters equally determined",
            },
        ],
    },

    "cat_moms": {
        "name": "Cat Moms",
        "emoji": "🐱",
        "description": "For cat owners, feline servants, and people whose cats run their lives",
        "simbolo_angolo": "tiny cat paw print stylized decorative element",
        "simbolo_lato": "small cute cat face with whiskers",
        "subjects": [
            {
                "key": "laptop_cat",
                "label": "Il Gatto sul Laptop",
                "simbolo_angolo": "tiny cat paw print stylized decorative element",
                "simbolo_lato": "small cute cat face with whiskers",
                "soggetto_kawaii": "one kawaii cat sitting directly in the center of a laptop keyboard with absolute confidence, owner trying to work around the cat who has knocked over the coffee and is now happily grooming, the laptop screen showing 'asdjkl;;;' from cat walking",
            },
            {
                "key": "3am_zoomies",
                "label": "Le Zoomies delle 3",
                "simbolo_angolo": "tiny moon with cat silhouette stylized decorative element",
                "simbolo_lato": "small cute cat running at speed",
                "soggetto_kawaii": "one kawaii cat in full zoomies mode at 3am — speed lines everywhere, tiny tornado of energy — while the owner sits up in bed with a pillow pressed to their face, utterly resigned, a clock showing 3:00am",
            },
            {
                "key": "everything_pushed",
                "label": "Niente È al Sicuro",
                "simbolo_angolo": "tiny cup falling off table stylized decorative element",
                "simbolo_lato": "small cute paw hovering over object",
                "soggetto_kawaii": "one intensely focused kawaii cat making deliberate eye contact while slowly pushing objects off a shelf one by one — a glass, a vase, car keys — with a serene expression, owner watching in helpless horror from below",
            },
            {
                "key": "cat_judgment",
                "label": "Sguardo di Giudizio",
                "simbolo_angolo": "tiny cat silhouette judging from above stylized decorative element",
                "simbolo_lato": "small cute cat eye with monocle",
                "soggetto_kawaii": "one kawaii cat sitting in the perfect loaf position, staring with supreme judgment at their human doing something mundane — eating cereal, watching TV — the cat's expression conveying deep disappointment in their choice of servant",
            },
            {
                "key": "fur_everywhere",
                "label": "Pelo Ovunque",
                "simbolo_angolo": "tiny lint roller as a trophy stylized decorative element",
                "simbolo_lato": "small cute fur clump with face",
                "soggetto_kawaii": "one kawaii cat owner wearing a beautiful black outfit absolutely covered in cat hair, the cat sitting nearby looking proud, tiny fur tufts floating like snowflakes through the air, a useless lint roller in the owner's defeated hand",
            },
            {
                "key": "cat_servant",
                "label": "Servo del Gatto",
                "simbolo_angono": "tiny crown on cat throne stylized decorative element",
                "simbolo_angolo": "tiny crown on cat throne stylized decorative element",
                "simbolo_lato": "small cute cat scepter with paw",
                "soggetto_kawaii": "one kawaii cat sitting regally on a plush throne while their human serves them on a silver platter, the cat wearing a tiny crown, looking appropriately unimpressed, multiple portraits of the cat on the walls behind the servant",
            },
        ],
    },

    "gym_bros": {
        "name": "Gym Bros",
        "emoji": "💪",
        "description": "For fitness fanatics, protein addicts, and people who never skip arm day",
        "simbolo_angolo": "tiny dumbbell with flexing arm stylized decorative element",
        "simbolo_lato": "small cute protein shake with muscles",
        "subjects": [
            {
                "key": "leg_day_skip",
                "label": "Leg Day? Mai Sentito",
                "simbolo_angolo": "tiny dumbbell with flexing arm stylized decorative element",
                "simbolo_lato": "small cute protein shake with muscles",
                "soggetto_kawaii": "one kawaii gym character with impossibly huge upper body and tiny chicken legs, completely unaware of the imbalance, flexing proudly in front of a mirror, other gym-goers staring politely away",
            },
            {
                "key": "mirror_selfie",
                "label": "Il Selfie allo Specchio",
                "simbolo_angolo": "tiny phone with gym selfie stylized decorative element",
                "simbolo_lato": "small cute flexing bicep with camera",
                "soggetto_kawaii": "one kawaii gym character taking their 47th gym mirror selfie from the exact same angle, a wall of previous identical selfies behind them, slightly different protein shake in each, all posted to social media with serious expression",
            },
            {
                "key": "protein_obsession",
                "label": "La Proteina Sacra",
                "simbolo_angolo": "tiny protein tub with halo stylized decorative element",
                "simbolo_lato": "small cute protein scoop with wings",
                "soggetto_kawaii": "one kawaii gym character's entire home covered in protein products — protein powder, protein bars, protein water — carefully calculating macros on a tiny calculator, surrounded by empty containers, expression of pure dedication",
            },
            {
                "key": "gym_closed",
                "label": "La Palestra È Chiusa",
                "simbolo_angolo": "tiny closed gym sign with tears stylized decorative element",
                "simbolo_lato": "small cute lock with sad dumbbells",
                "soggetto_kawaii": "one devastated kawaii gym character standing in front of a closed gym, hands on the glass door, dramatic rain falling around them, meanwhile the gym is closed for just one hour for cleaning",
            },
            {
                "key": "supplement_cabinet",
                "label": "Il Cabinet dei Supplementi",
                "simbolo_angolo": "tiny cabinet overflowing with supplements stylized decorative element",
                "simbolo_lato": "small cute pill bottle with muscles",
                "soggetto_kawaii": "one overwhelmed kawaii character opening their supplement cabinet and being buried under an avalanche of protein tubs, creatine, BCAAs, pre-workout, collagen — hundreds of products with faces — all carefully organized and labeled",
            },
            {
                "key": "no_pain_no_gain",
                "label": "No Pain No Gain",
                "simbolo_angolo": "tiny fire with dumbbell stylized decorative element",
                "simbolo_lato": "small cute sweat drop with determination",
                "soggetto_kawaii": "one kawaii gym character in obvious pain doing one final rep, imagining themselves as a heroic warrior, dramatic victory pose fantasy floating in a thought bubble above while their actual expression is pure suffering and glory",
            },
        ],
    },
}

NICHE_ORDER = list(NICHES.keys())
